export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const INFOS_ROUTER = '/infos'
export const INFO_PAGE_ROUTER = INFOS_ROUTER
export const ALBUMS_ROUTER = INFOS_ROUTER + '/albums';
export const ALBUMS_PAGE_ROUTER = ALBUMS_ROUTER 
export const NEWS_ROUTER = INFOS_ROUTER + '/news';
export const NEWS_PAGE_ROUTER = NEWS_ROUTER
export const REVIEWS_ROUTER = '/review'
export const SERVICES_ROUTER = '/service'
export const HOTELS_ROUTER = SERVICES_ROUTER + '/hotels';
export const ROOMS_ROUTER = HOTELS_ROUTER + '/rooms';
export const ROOM_ROUTER = '/hotels' + '/room';
export const TYPES_ROUTER = ADMIN_ROUTER
export const SERVICES_PAGE_ROUTER = SERVICES_ROUTER
export const MAIN_ROUTER = '/'
export const ADMIN_REVIEWS_ROUTER = '/admin_reviews'
